// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1unA2d1cSdT2wQRZhJ_e6psjSMMHyPRY',
    appId: '1:1073406010065:web:a4c4f1c26d338a78c69bf0',
    messagingSenderId: '1073406010065',
    projectId: 'fooddelivery-8a369',
    authDomain: 'fooddelivery-8a369.firebaseapp.com',
    storageBucket: 'fooddelivery-8a369.appspot.com',
    measurementId: 'G-54FMXR2N5V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL7V6qONCFX-P_qTgEiPjuaTbXzdShKlY',
    appId: '1:1073406010065:android:a65d6220a14d755ac69bf0',
    messagingSenderId: '1073406010065',
    projectId: 'fooddelivery-8a369',
    storageBucket: 'fooddelivery-8a369.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgVgiyk42aXiLdmWEyH_zzGNOOcPcO2Gk',
    appId: '1:1073406010065:ios:330c3934a67a384ec69bf0',
    messagingSenderId: '1073406010065',
    projectId: 'fooddelivery-8a369',
    storageBucket: 'fooddelivery-8a369.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgVgiyk42aXiLdmWEyH_zzGNOOcPcO2Gk',
    appId: '1:1073406010065:ios:330c3934a67a384ec69bf0',
    messagingSenderId: '1073406010065',
    projectId: 'fooddelivery-8a369',
    storageBucket: 'fooddelivery-8a369.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1unA2d1cSdT2wQRZhJ_e6psjSMMHyPRY',
    appId: '1:1073406010065:web:ef9a5ec213dc94e3c69bf0',
    messagingSenderId: '1073406010065',
    projectId: 'fooddelivery-8a369',
    authDomain: 'fooddelivery-8a369.firebaseapp.com',
    storageBucket: 'fooddelivery-8a369.appspot.com',
    measurementId: 'G-PS89ECW659',
  );
}
